# ----- params ----- #

# ska options
ska:
  fastq_qual: 20
  fastq_cov: 4
  kmer: 31
  single_strand: false
  freq_filter: 0.9

# IQ-TREE options
iqtree:
  model: GTR+G+ASC
  alternative: GTR+G

# snps2te
# this is for kpneumoniae
# based on within patient snps accumulation
# set-back: we miss MGE transfer/loss with this
#snps_day_ratio: 0.04 
snps_day_ratio: 0.08
min_snps: 5

# min cluster size
min_cluster_size: 3

# ----- inputs ----- #
# already there produced outisde the pipeline
# data
data: "data/data.tsv"

# poppunk
poppunk_rfile: "poppunk_input.txt"
poppunk_clusters: "out/poppunk/poppunk_clusters/poppunk_clusters_clusters.csv"
poppunk_h5: "out/poppunk/Klebsiella_pneumoniae_v3_full/Klebsiella_pneumoniae_v3_full.h5"

# strians cluster directory
strains_dir: "out/clusters/"


