# ----- params ----- #

# ska options
ska:
  fastq_qual: 20
  fastq_cov: 4
  kmer: 31
  single_strand: false
  freq_filter: 0.9

# IQ-TREE options
iqtree:
  model: GTR+G+ASC
  alternative: GTR+G

# snps2te
snps_day_ratio: 0.08
min_snps: 5

# min poppunk cluster size
min_cluster_size: 3

# ----- inputs ----- #
# already there produced outisde the pipeline
# data
data: "data/data.tsv"

# poppunk
poppunk_rfile: "poppunk_input_all.txt"
poppunk_clusters: "klebsiella_clusters.csv"
poppunk_validclusters: "poppunk_validclusters.txt"
poppunk_h5: "/vol/projects/jburgaya/storage/Klebsiella_pneumoniae_v3_refs"

# strians cluster directory
strains_dir: "out/clusters/"


